apiVersion: v1 
kind: Namespace 
metadata:
  name: roboshop 
---
# creating role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role 
metadata: 
  name: roboshop-k8-admin
  namespace: roboshop 
rules:
  #- apiGroups: [""]-> represents core-group api which is v1 
   - apiGroups: ["*"]
     resources: ["*"]
     verbs: ["*"]

--- 
# creating rolebinding to add the above role to the user
apiVersion : rbac.authorization.k8s.io/v1 
kind: RoleBinding 
metadata: 
  name: roboshop-k8-admin-role-binding 
  namespace: roboshop 
subjects:
  - kind: User 
    name: k8s-admin  #give iam user-name
    apiGroup:  rbac.authorization.k8s.io 
roleRef: 
  kind: Role 
  name: roboshop-k8-admin
  apiGroup: rbac.authorization.k8s.io


