apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::730335449261:role/eksctl-rs-app-nodegroup-spot-insta-NodeInstanceRole-I4hSTB5phxvs
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::730335449261:user/k8s-admin
      username: k8s-admin 
    - userarn: arn:aws:iam::730335449261:user/k8s-traine 
      username: k8s-traine 
    - userarn: arn:aws:iam::730335449261:user/k8s-dev-access
      username: k8s-dev-access 
kind: ConfigMap
metadata:
  creationTimestamp: "2024-02-19T16:01:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1174"
  uid: e708210f-0f70-4326-82b3-d4efac45d90

  #kubectl get configmap aws-auth -n kube-system
  #kubectl edit configmap aws-auth -n kube-system 
