apiVersion: v1 
kind: ClusterConfig 
metadata:
  name: newclstr
  region: eu-north-1
managedNodeGroups:
  - name: ng-1
    instance_type: t3.micro 
    minSize: 1 
    maxSize: 3
    ssh:
     publicKeyName: intel 