apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig 
metadata:
  name: newclstr
  region: eu-north-1
managedNodeGroups:
  - name: ng-1
    instanceType: t3.micro 
    minSize: 2
    maxSize: 4
    desiredCapacity: 2
    ssh:
     publicKeyName: intel 
