apiVersion: v1 
kind: Pod 
metadata: 
  name: nginx-test 
spec: 
 containers:
   - image: nginx 
     name: nginx 
     ports: 
      - containerPort: 80 
     volumeMounts:
       - name: test-volume 
         mountPath: /var/log/nginx/
 volumes: 
   - name: test-volume 
     emptyDir: {}

---


apiVersion: v1 
kind: Pod 
metadata: 
  name: nginx-test 
spec: 
 containers:
   - image: nginx 
     name: nginx 
     ports: 
      - containerPort: 80 
     volumeMounts:
       - name: test-volume 
         mountPath: /var/log/nginx/
   - image: busybox
     name: busy 
     command: ["sh", "-c", "while true; do cat /var/log/nginx/error.log; sleep 30; done"]
     volumeMounts: 
        - name: test-volume
          mountPath: /var/log/nginx
 volumes: 
   - name: test-volume 
     emptyDir: {}


