apiVersion: v1
kind: Pod 
metadata:
 name: nginx-pod 
spec:
 containers: 
   - image: nginx 
     name: nginx 
     ports: 
       - containerPort: 80 
 nodeSelector:
     tier: web



#syntax to set labels to the nodes
#kubectl labels node node-name tier=web