apiVersion: v1 
kind: Pod 
metadata:
  name: nginx-pod 
spec: 
 containers: 
      - image: nginx 
        name: nginx 
        ports: 
         - containerPort: 80 
 affinity:
   nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
         - matchExpressions:
             - key: tier
               operator: In 
               values:
                - web-server


# if the labels like tier=web--server didn't match in any of the nodes, the scheduler will not shcedule the pods, it's in pending state.
    