apiVersion: v1 
kind: Pod 
metadata:
  name: nginx-pod 
spec: 
 containers: 
      - image: nginx 
        name: nginx 
        ports: 
         - containerPort: 80 
 affinity:
   nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
         - matchExpressions:
             - key: tier
               operator: NotIn
               values:
                - web-server

# nodeantiaffinity-behaviour
#===========================
# the pod will get schedule on the nodes where it doesn't have the label tier=websever, 


