apiVersion: v1 
kind: Pod 
metadata: 
  name: nginx-pod 
spec:
 containers:
   - image: nginx 
     name: nginx 
     volumeMounts:
       - name: shared-logs 
         mountPath: /var/log/nginx 
   - image: busybox 
     name: sidecar 
     command: ["sh", "-c", "while true; do cat /var/log/nginx/access.log; sleep 30; done"]
     volumeMounts:
       - name: shared-logs 
         mountPath: /var/log/nginx
 volumes:
    - name: shared-logs 
      emptyDir: {}
#

# 1) In Kubernetes, an emptyDir is a type of volume that is created and managed by the Kubernetes 
# system. It is essentially a temporary storage volume that is created when a Pod is scheduled 
# on a node and exists for the lifetime of that Pod. The emptyDir volume is initially empty 
# and is deleted when the Pod is terminated or rescheduled elsewhere.

# Temporary Storage: 
# An emptyDir volume provides temporary storage space for a Pod's containers. It is useful 
# for scenarios where containers within the same Pod need to share files or data temporarily 
# during the Pod's lifetime.

# Lifecycle Bound to Pod: 
# The emptyDir volume is created when the Pod is scheduled on a node and exists as long as
#  the Pod is running on that node. When the Pod is deleted or evicted from the node, the 
#  emptyDir volume and its contents are also deleted.

#  Shared Volume: 
 #   All containers within the same Pod can access and modify the contents of the
#   emptyDir volume. This makes it suitable for scenarios where containers need to share 
#   temporary files or data between them.

#   Usage: 
#   Common use cases for emptyDir volumes include sharing files between containers 
#   in a Pod, caching data for faster access, or storing temporary data that is not critical to preserve.

# #

    