apiVersion: v1 
kind: Pod 
metadata: 
  name: nginx-pod 
spec:
 containers:
   - image: nginx 
     name: nginx 
     volumeMounts:
       - name: shared-logs 
         mountPath: /var/log/nginx 
   - image: busybox 
     name: sidecar 
     command: ["sh", "-c", "while true; do cat /var/log/nginx/access.log; sleep 30; done"]
     volumeMounts:
       - name: shared-logs 
         mountPath: /var/log/nginx
 volumes:
    - name: shared-logs 
      emptyDir: {}
    