apiVersion: v1 
kind: ConfigMap 
metadata:
  name: nginx-config 
data: 
 nginx.conf: |
   # configuration is loading from config-map
   user  nginx;
   worker_processes  auto;

   error_log  /var/log/nginx/error.log notice;
   pid        /var/run/nginx.pid;


   events {
    worker_connections  1024;
   }


   http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
   } 
--- 

apiVersion: v1 
kind: Pod 
metadata: 
  name: nginx-web 
spec: 
 containers:
   - image: nginx 
     name: nginx 
     ports: 
       - containerPort: 80 
     volumeMounts: 
       - name: nginx-config 
         mountPath: /etc/nginx/nginx.conf
         subPath: nginx.conf
 volumes: 
   - name: nginx-config 
     configMap:
        name: nginx-config
        items: 
          - key: nginx.conf 
            path: nginx.conf

            