apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: filebeat 
data: 
  filebeat.yaml : | 
      filebeat.inputs: 
       - type: log 
         enables: true 
         paths: 
          - /var/log/nginx/access.log 
          - /var/log/nginx/error/log 
      output.elasticsearch:
          hosts: ["elasticsearch:9200"]
--- 

apiVersion: v1 
kind: Pod 
metadata: 
  name: pod-file 
spec: 
 containers: 
   - image: nginx 
     name: nginx 
     ports: 
     - containerPort: 80 
     volumeMounts: 
        - name: nginx-log 
          mountPath: /var/log/nginx 
   - image: docker.elastic.co/beats/filebeat:7.16.3
     name: filebeat 
     volumeMounts: 
       - name: filebeat-config
         mountPath: /usr/share/filebeat/filebeat.yaml 
         subPath: filebeat.yaml 
       - name: nginx-log 
         mountPath: /var/log/nginx 

 volumes: 
    - name: filebeat-config 
      configMap:
        name: filebeat 
    - name: nginx-log 
      emptyDir: {}  

# the filebeat fetch the logs from nginx and push to the elk

