apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx2-deploy 
  labels:
    app: nginx-sever 
spec: 
 replicas: 2
 selector: 
   matchLabels: 
     tier: nginx-deployment 
 template: 
   metadata: 
     labels:
       tier: nginx-deployment 
   spec: 
     containers: 
       - image: devopshandson3/deployment:v2
         name: app-v2
         ports: 
           - containerPort: 80
         livenessProbe:
           httpGet:
             path: /
             port: 80 
           initialDelaySeconds: 15 
           periodSeconds: 10 
         
          
 

    
    
