apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    tier: web-server
spec:
 containers:
   - image: nginx
     name: nginx
     ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
 type: LoadBalancer
 selector:
  tier: web-server
 ports:
  - protocol: TCP
    port: 80   #--service-port
    targetPort: 80  #---target containerport

---

apiVersion: v1
kind: Pod
metadata:
  name: almalinux
spec:
  containers:
     - image: almalinux
       name: alma
       command: ["sleep", "650"]
---

# login into alma pod and you call nginx pod by using nginx-service endpoint : http://nginx-service
