apiVersion: v1 
kind: LimitRange 
metadata: 
  name: limit-resources 
  namespace: spot-ns
sepc: 
limits:
 - type: container 
   default: 
     cpu: "500m"      # maximum 
   defaultRequest:    #minimum
     cpu: "250m"
   max:
    cpu: "750m"     #regardless default, max ==> value > maxium 
   min: 
    cpu: "150m"    #regardless defaultrequest, min ==> value > min 

  
    