apiVersion: v1 
kind: Service 
metadata: 
  name: nginx-service 
  labels:
    service: web-server 
spec: 
  type: NodePort
  selector: 
    tier: nginx-deployment 
  ports: 
    - protocol: TCP
      port: 80   #--service-port
      targetPort: 80  #---target containerport




