apiVersion: apps/v1 
kind: Deployment 
metadata:
 name: nginx-deploy
spec:
 replicas: 4 
 selector:
   matchLabels:
    tier: app 
 template: 
   metadata:
    labels: 
     tier: app 
   spec: 
    containers:
      - image: nginx 
        name: nginx 
        ports:
         - containerPort: 80

         