apiVersion: v1 
kind: Pod 
metadata: 
  name: k8-pod  # this is pod name 
  namespace: eks-namespace
spec:
  containers:
    - name: nginx 
      image: nginx 
      ports:
        - containerPort: 80 

#kubectl get pods -n eks-namespace --will get the list of pods which are in eks-namespace