apiVersion: v1 
kind: Pod 
metadata: 
  name: k8-pod  # this is pod name 
  namespace: eks-namespace
spec:
  containers:
    - name: nginx 
      image: nginx 
      imagePullPolicy: Always
      ports:
        - containerPort: 80 

#imagePullPolicy: will always try to fetch the image if it's not present