apiVersion: v1 
kind: Pod 
metadata: 
  name: k8-pod  # this is pod name 
  namespace: eks-namespace
spec:
  containers:
    - name: nginx 
      image: nginx 
      imagePullPolicy: Always
      ports:
        - containerPort: 80 
      resources:
        requests:      # soft --> min
          cpu: "75m"
          memory: "120Mi"
        limits:      # hard    --> max 
          cpu: "80m"
          memory: "125Mi"

  # By default containers will use all the resources from the host system
  # In kunernetes , we are setting the limit resources , requests is the min 
  # limits is the max , more tham limits container will not take , it can only take upto what we defined in limits 