apiVersion: v1 
kind: Pod 
metadata: 
  name: nginx-pod
  labels:
    author: krishnaTeja 
    project: practice 
spec:
 containers: 
   - name: nginx 
     image: nginx 
     ports: 
       - containerPort: 80 