apiVersion: v1 
kind: Pod 
metadata: 
  name: k8-pod  # this is pod name 
spec:
  containers:
    - name: nginx 
      image: nginx 
      ports:
        - containerPort: 80 
      env:
       - name: tier 
         value: server 
       - name: appid 
         value: "12987"

