apiVersion: v1 
kind: Pod 
metadata: 
  name: nginxpod 
spec: 
 containers: 
   - name: nginx 
     image: nginx 
     ports: 
      - containerPort: 80 
     env: 
      - name: username 
        valueFrom:
         secretKeyRef:
           name: app-secrets
           key: username 
      - name: passwrod 
        valueFrom:
          secretKeyRef:
            name: app-secrets
            key: password